-- AlterTable
ALTER TABLE "Reading" ADD COLUMN     "n0_3" INTEGER,
ADD COLUMN     "n0_5" INTEGER,
ADD COLUMN     "n10" INTEGER,
ADD COLUMN     "n1_0" INTEGER,
ADD COLUMN     "n2_5" INTEGER,
ADD COLUMN     "n5_0" INTEGER;

